# Generated by Django 5.1.2 on 2026-01-13 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='设备编号')),
                ('production_line', models.CharField(max_length=100, verbose_name='所属产线')),
                ('process', models.CharField(max_length=100, verbose_name='工序')),
                ('part_details', models.TextField(blank=True, null=True, verbose_name='设备零部件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='excel_files/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Excel上传',
                'verbose_name_plural': 'Excel上传',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(max_length=50, verbose_name='序号')),
                ('month', models.CharField(max_length=20, verbose_name='月份')),
                ('production_line', models.CharField(max_length=100, verbose_name='产线')),
                ('process', models.CharField(max_length=100, verbose_name='工序')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='设备或工装名称')),
                ('equipment_code', models.CharField(max_length=100, verbose_name='设备编号')),
                ('equipment_part', models.CharField(max_length=200, verbose_name='设备零部件/部位')),
                ('change_reason', models.CharField(choices=[('故障维修', '故障维修'), ('定期保养', '定期保养'), ('设备改造', '设备改造'), ('零件更换', '零件更换'), ('其他', '其他')], max_length=50, verbose_name='变更原因')),
                ('status_before', models.TextField(verbose_name='变更前(现状)')),
                ('status_after', models.TextField(verbose_name='变更后（变了什么）')),
                ('start_datetime', models.DateTimeField(verbose_name='开始日期及时间')),
                ('end_datetime', models.DateTimeField(verbose_name='结束日期及时间')),
                ('duration', models.DurationField(verbose_name='耗用时长')),
                ('parts_consumables', models.TextField(blank=True, null=True, verbose_name='零件耗材')),
                ('implementer', models.CharField(max_length=100, verbose_name='实施人')),
                ('confirm_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='确认人')),
                ('acceptor', models.CharField(blank=True, max_length=100, null=True, verbose_name='验收人')),
                ('effect_evaluation', models.TextField(blank=True, null=True, verbose_name='效果评价')),
                ('evaluator', models.CharField(blank=True, max_length=100, null=True, verbose_name='评价人')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('shift_type', models.CharField(choices=[('早班', '早班'), ('中班', '中班'), ('晚班', '晚班'), ('长白班', '长白班'), ('其他', '其他')], max_length=20, verbose_name='班次')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('imported_from_excel', models.BooleanField(default=False, verbose_name='是否从Excel导入')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('excel_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excelhandler.excelupload', verbose_name='Excel上传记录')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelhandler.equipment', verbose_name='设备')),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelhandler.maintenancerecord', verbose_name='维修记录')),
            ],
            options={
                'verbose_name': '维修历史',
                'verbose_name_plural': '维修历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
