# Generated by Django 5.1.2 on 2026-01-13 02:34

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenanceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('equipment_part', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备部件')),
                ('maintenance_procedure', models.TextField(verbose_name='维修步骤')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='参数')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片')),
                ('videos', models.JSONField(blank=True, default=list, verbose_name='视频')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备维修资料库',
                'verbose_name_plural': '设备维修资料库',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.IntegerField(unique=True, verbose_name='序号')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('production_line', models.CharField(max_length=100, verbose_name='产线')),
                ('process', models.CharField(max_length=100, verbose_name='工序')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='设备或工装名称')),
                ('equipment_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备编号')),
                ('equipment_part', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备零部件/部位')),
                ('change_reason', models.CharField(max_length=200, verbose_name='变更原因')),
                ('before_change', models.TextField(blank=True, verbose_name='变更前(现状）')),
                ('after_change', models.TextField(blank=True, verbose_name='变更后（变了什么）')),
                ('start_time', models.DateTimeField(verbose_name='开始日期及时间')),
                ('end_time', models.DateTimeField(verbose_name='结束日期及时间')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='耗用时长')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='耗用时长(分钟)')),
                ('spare_parts_consumed', models.TextField(blank=True, verbose_name='零件耗材')),
                ('implementers', models.TextField(help_text='可以输入多个协助人，用逗号分隔', verbose_name='实施人')),
                ('verifiers', models.TextField(blank=True, help_text='可以输入多个确认人，用逗号分隔', verbose_name='确认人')),
                ('acceptors', models.TextField(blank=True, help_text='可以输入多个验收人，用逗号分隔', verbose_name='验收人')),
                ('evaluators', models.TextField(blank=True, help_text='可以输入多个评价人，用逗号分隔', verbose_name='评价人')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('shift_type', models.CharField(choices=[('long_day_shift', '长白班'), ('rotating_shift', '倒班')], max_length=20, verbose_name='班次类型')),
                ('plant_phase', models.CharField(choices=[('phase_1', '一期'), ('phase_2', '二期')], max_length=20, verbose_name='工厂分期')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_phase', models.CharField(choices=[('phase_1', '一期'), ('phase_2', '二期')], default='phase_1', max_length=20)),
                ('shift_type', models.CharField(choices=[('long_day_shift', '长白班'), ('rotating_shift', '倒班')], default='long_day_shift', max_length=20)),
                ('can_add', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=True)),
                ('can_delete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
