# Generated by Django 5.1.2 on 2026-01-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipmentMaintenanceLibrary',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
    ]
