# Generated by Django 5.1.2 on 2026-01-12 13:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('subdomain', models.CharField(max_length=250)),
                ('max_assets', models.IntegerField(default=3)),
                ('max_users', models.IntegerField(default=2)),
                ('max_active_orders', models.IntegerField(default=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('ref', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Equipment', 'Equipment'), ('Building', 'Building'), ('Furniture', 'Furniture'), ('IT', 'IT'), ('Other', 'Other')], default='Other', max_length=100)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('serial_number', models.CharField(default='', max_length=100)),
                ('warranty_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('running_hour_consumption_kw', models.FloatField(blank=True, default=0)),
                ('on_hour_consumption_kw', models.FloatField(blank=True, default=0)),
                ('running_hour_cost', models.FloatField(blank=True, default=0)),
                ('on_hour_cost', models.FloatField(blank=True, default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance'), ('Retired', 'Retired')], default='Active', max_length=50)),
                ('state', models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off'), ('run', 'run'), ('stop', 'stop'), ('out of order', 'out of order'), ('resume out of order', 'resume out of order'), ('failure', 'failure'), ('resume failure', 'resume failure'), ('break in', 'break in'), ('resume break in', 'resume break in'), ('break out', 'break out'), ('resume break out', 'resume break out'), ('fault', 'fault'), ('resume fault', 'resume fault'), ('report', 'report')], default='', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('ref', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('planned_starting_date', models.DateTimeField(blank=True, null=True)),
                ('planned_finished', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.FileField(blank=True, null=True, upload_to='instructions')),
                ('type', models.CharField(choices=[('Planned', 'Planned'), ('Other', 'Other'), ('UnPlanned', 'UnPlanned')], default='Planned', max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('type', models.CharField(choices=[('Admin', 'Admin'), ('Reporter', 'Reporter')], default='Admin', max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
