# Generated by Django 5.1.2 on 2026-01-13 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='on_hour_consumption_kw',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='on_hour_cost',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='running_hour_consumption_kw',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='running_hour_cost',
        ),
        migrations.CreateModel(
            name='MaintenanceCase',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process', models.CharField(choices=[('molding', '成型工段'), ('assembly', '装配工段'), ('packaging', '包装工段'), ('quality_control', '质量控制'), ('maintenance', '维修工段'), ('other', '其他')], max_length=50, verbose_name='工段')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('fault_reason', models.TextField(verbose_name='故障原因')),
                ('fault_phenomenon', models.TextField(verbose_name='故障现象')),
                ('fault_handling_method', models.TextField(verbose_name='故障处理方法')),
                ('images', models.ImageField(blank=True, null=True, upload_to='maintenance_cases/images/', verbose_name='故障图片')),
                ('videos', models.FileField(blank=True, null=True, upload_to='maintenance_cases/videos/', verbose_name='故障视频')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
            options={
                'verbose_name': '维修故障案例',
                'verbose_name_plural': '维修故障案例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceManual',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_line', models.CharField(choices=[('1-1#', '1-1#'), ('1-2#', '1-2#'), ('1-3#', '1-3#'), ('1-4#', '1-4#'), ('1-5#', '1-5#'), ('1-6#', '1-6#'), ('1-7#', '1-7#'), ('1-8#', '1-8#'), ('1-9#', '1-9#'), ('1-10#', '1-10#'), ('2-1#', '2-1#'), ('2-2#', '2-2#'), ('2-3#', '2-3#'), ('2-4#', '2-4#'), ('2-5#', '2-5#'), ('2-6#', '2-6#'), ('2-7#', '2-7#'), ('2-8#', '2-8#'), ('2-9#', '2-9#')], max_length=10, verbose_name='生产线')),
                ('process', models.CharField(choices=[('molding', '成型工段'), ('assembly', '装配工段'), ('packaging', '包装工段'), ('quality_control', '质量控制'), ('maintenance', '维修工段'), ('other', '其他')], max_length=50, verbose_name='工段')),
                ('equipment_name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('title', models.CharField(max_length=255, verbose_name='手册标题')),
                ('description', models.TextField(verbose_name='手册描述')),
                ('repair_steps', models.TextField(verbose_name='维修步骤')),
                ('images', models.ImageField(blank=True, null=True, upload_to='maintenance_manuals/images/', verbose_name='图片')),
                ('videos', models.FileField(blank=True, null=True, upload_to='maintenance_manuals/videos/', verbose_name='视频')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
            options={
                'verbose_name': '维修手册',
                'verbose_name_plural': '维修手册',
                'ordering': ['production_line', 'process', 'equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('phase_1', '一期'), ('phase_2', '二期')], max_length=20, verbose_name='工厂分期')),
                ('shift', models.CharField(choices=[('long_day_shift', '长白班'), ('rotating_shift', '倒班')], max_length=20, verbose_name='班次')),
                ('production_line', models.CharField(choices=[('1-1#', '1-1#'), ('1-2#', '1-2#'), ('1-3#', '1-3#'), ('1-4#', '1-4#'), ('1-5#', '1-5#'), ('1-6#', '1-6#'), ('1-7#', '1-7#'), ('1-8#', '1-8#'), ('1-9#', '1-9#'), ('1-10#', '1-10#'), ('2-1#', '2-1#'), ('2-2#', '2-2#'), ('2-3#', '2-3#'), ('2-4#', '2-4#'), ('2-5#', '2-5#'), ('2-6#', '2-6#'), ('2-7#', '2-7#'), ('2-8#', '2-8#'), ('2-9#', '2-9#')], max_length=10, verbose_name='生产线')),
                ('title', models.CharField(max_length=255, verbose_name='维修标题')),
                ('description', models.TextField(verbose_name='维修描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', '开启'), ('in_progress', '进行中'), ('completed', '完成'), ('cancelled', '取消')], default='open', max_length=20, verbose_name='状态')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.asset', verbose_name='设备')),
                ('assistant_operators', models.ManyToManyField(blank=True, related_name='maintenances_assisted', to=settings.AUTH_USER_MODEL, verbose_name='协助人员')),
                ('main_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_led', to=settings.AUTH_USER_MODEL, verbose_name='主操作员')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.organization')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'ordering': ['-start_time'],
            },
        ),
    ]
