# Generated by Django 5.1.2 on 2026-01-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_asset_on_hour_consumption_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='phase',
            field=models.CharField(blank=True, choices=[('一期', '一期'), ('二期', '二期')], max_length=10, null=True, verbose_name='工厂期数'),
        ),
        migrations.AddField(
            model_name='asset',
            name='process',
            field=models.CharField(blank=True, choices=[('PL', 'PL'), ('N1', 'N1'), ('N2', 'N2'), ('S1', 'S1'), ('F1', 'F1'), ('F2', 'F2'), ('CF', 'CF'), ('B', 'B'), ('BZ', 'BZ')], max_length=10, null=True, verbose_name='工序'),
        ),
        migrations.AddField(
            model_name='asset',
            name='production_line',
            field=models.CharField(blank=True, choices=[('1#', '1#'), ('2#', '2#'), ('3#', '3#'), ('4#', '4#'), ('5#', '5#'), ('6#', '6#'), ('7#', '7#'), ('8#', '8#'), ('9#', '9#'), ('10#', '10#'), ('2-1#', '2-1#'), ('2-2#', '2-2#'), ('2-3#', '2-3#'), ('2-4#', '2-4#'), ('2-5#', '2-5#'), ('2-6#', '2-6#'), ('2-7#', '2-7#'), ('2-8#', '2-8#'), ('2-9#', '2-9#')], max_length=10, null=True, verbose_name='产线'),
        ),
    ]
