# Generated by Django 5.1.2 on 2026-01-13 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_asset_phase_alter_asset_process_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftMaintenanceRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(choices=[('phase_1', '一期'), ('phase_2', '二期')], max_length=20, verbose_name='工厂分期')),
                ('shift_type', models.CharField(choices=[('long_day_shift', '长白班'), ('rotating_shift', '倒班')], max_length=20, verbose_name='班次类型')),
                ('month', models.CharField(blank=True, max_length=10, null=True, verbose_name='月份')),
                ('production_line', models.CharField(blank=True, max_length=50, null=True, verbose_name='产线')),
                ('process', models.CharField(blank=True, max_length=50, null=True, verbose_name='工序')),
                ('equipment_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备或工装名称')),
                ('equipment_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备编号')),
                ('equipment_part', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备零部件/部位')),
                ('change_reason', models.CharField(blank=True, choices=[('maintenance', '维保'), ('repair', '维修'), ('technical_modification', '技改')], max_length=50, null=True, verbose_name='变更原因')),
                ('before_change', models.TextField(blank=True, null=True, verbose_name='变更前(现状）')),
                ('after_change', models.TextField(blank=True, null=True, verbose_name='变更后（变了什么）')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='开始日期及时间')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='结束日期及时间')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='耗用时长(分钟)')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.asset', verbose_name='关联资产')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='分配给')),
            ],
            options={
                'verbose_name': '班次维修记录',
                'verbose_name_plural': '班次维修记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
