# Generated by Django 5.1.2 on 2026-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_shiftmaintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftmaintenancerecord',
            name='acceptor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='验收人'),
        ),
        migrations.AddField(
            model_name='shiftmaintenancerecord',
            name='confirm_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='shiftmaintenancerecord',
            name='implementer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='实施人'),
        ),
        migrations.AddField(
            model_name='shiftmaintenancerecord',
            name='parts_consumables',
            field=models.TextField(blank=True, null=True, verbose_name='零件耗材'),
        ),
        migrations.AddField(
            model_name='shiftmaintenancerecord',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='shiftmaintenancerecord',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='序号'),
        ),
    ]
