# Generated by Django 5.1.2 on 2026-01-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_shiftmaintenancerecord_acceptor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='序号'),
        ),
    ]
