# Generated by Django 5.1.2 on 2026-01-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_alter_shiftmaintenancerecord_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plant_phase',
            field=models.CharField(blank=True, choices=[('phase_1', '一期'), ('phase_2', '二期')], max_length=20, null=True, verbose_name='工厂分期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('long_day_shift', '长白班'), ('rotating_shift', '倒班')], max_length=20, null=True, verbose_name='班次类型'),
        ),
    ]
