# Generated by Django 5.1.2 on 2026-01-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_userprofile_plant_phase_userprofile_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_assets',
            field=models.BooleanField(default=True, verbose_name='可添加设备'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_cases',
            field=models.BooleanField(default=False, verbose_name='可添加维修案例'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_maintenance_records',
            field=models.BooleanField(default=True, verbose_name='可添加维修记录'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_manuals',
            field=models.BooleanField(default=False, verbose_name='可添加维修手册'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_assets',
            field=models.BooleanField(default=False, verbose_name='可删除设备'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_cases',
            field=models.BooleanField(default=False, verbose_name='可删除维修案例'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_maintenance_records',
            field=models.BooleanField(default=False, verbose_name='可删除维修记录'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_manuals',
            field=models.BooleanField(default=False, verbose_name='可删除维修手册'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_assets',
            field=models.BooleanField(default=True, verbose_name='可编辑设备'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_cases',
            field=models.BooleanField(default=False, verbose_name='可编辑维修案例'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_maintenance_records',
            field=models.BooleanField(default=True, verbose_name='可编辑维修记录'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_manuals',
            field=models.BooleanField(default=False, verbose_name='可编辑维修手册'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Operator', 'Operator')], default='Admin', max_length=50),
        ),
    ]
