# Generated by Django 5.1.2 on 2026-01-15 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_userprofile_can_add_assets_userprofile_can_add_cases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='期数代码')),
                ('name', models.CharField(max_length=50, verbose_name='期数名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工厂分期',
                'verbose_name_plural': '工厂分期',
                'db_table': 'plant_phase_config',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工序代码')),
                ('name', models.CharField(max_length=50, verbose_name='工序名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'db_table': 'process_config',
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='产线代码')),
                ('name', models.CharField(max_length=50, verbose_name='产线名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.plantphase', verbose_name='所属期数')),
            ],
            options={
                'verbose_name': '产线',
                'verbose_name_plural': '产线',
                'db_table': 'production_line_config',
                'unique_together': {('code', 'phase')},
            },
        ),
    ]
