# Generated by Django 5.1.2 on 2026-01-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_plantphase_process_productionline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.plantphase', verbose_name='工厂分期'),
        ),
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.process', verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.productionline', verbose_name='产线'),
        ),
    ]
