# Generated by Django 5.1.2 on 2026-01-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_alter_shiftmaintenancerecord_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='班次代码')),
                ('name', models.CharField(max_length=50, verbose_name='班次名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '班次类型',
                'verbose_name_plural': '班次类型',
                'db_table': 'shift_type_config',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.plantphase', verbose_name='期数'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.process', verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.productionline', verbose_name='产线'),
        ),
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='process',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='production_line',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='产线'),
        ),
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.shifttype', verbose_name='班次类型'),
        ),
    ]
