# Generated by Django 5.1.2 on 2026-01-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_shifttype_alter_asset_phase_alter_asset_process_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='images',
        ),
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='repair_steps',
        ),
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='videos',
        ),
        migrations.CreateModel(
            name='MaintenanceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='步骤序号')),
                ('title', models.CharField(max_length=255, verbose_name='步骤标题')),
                ('description', models.TextField(verbose_name='步骤描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='maintenance_steps/images/', verbose_name='步骤图片')),
                ('video', models.FileField(blank=True, null=True, upload_to='maintenance_steps/videos/', verbose_name='步骤视频')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='db.maintenancemanual', verbose_name='所属手册')),
            ],
            options={
                'verbose_name': '维修步骤',
                'verbose_name_plural': '维修步骤',
                'ordering': ['manual', 'step_number'],
            },
        ),
    ]
