# Generated by Django 5.1.2 on 2026-01-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_remove_maintenancemanual_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancemanual',
            name='process',
            field=models.CharField(max_length=50, verbose_name='工段'),
        ),
    ]
