# Generated by Django 5.1.2 on 2026-01-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_alter_maintenancemanual_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancemanual',
            name='production_line',
            field=models.CharField(max_length=10, verbose_name='生产线'),
        ),
    ]
