# Generated by Django 5.1.2 on 2026-01-16 09:44

import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_alter_maintenancemanual_production_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftmaintenancerecord',
            name='duration',
            field=models.FloatField(blank=True, null=True, verbose_name='耗用时长(小时)'),
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('task_description', models.TextField(blank=True, verbose_name='任务计划')),
                ('planned_people_count', models.IntegerField(default=0, verbose_name='计划人数')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.FloatField(default=0.0, verbose_name='完成进度(%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assigned_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='任务实施人')),
            ],
            options={
                'verbose_name': '任务计划',
                'verbose_name_plural': '任务计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
