# Generated by Django 5.1.2 on 2026-01-16 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_alter_shiftmaintenancerecord_duration_taskplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskplan',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.plantphase', verbose_name='期别'),
        ),
        migrations.AddField(
            model_name='taskplan',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.process', verbose_name='工序'),
        ),
        migrations.AddField(
            model_name='taskplan',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.productionline', verbose_name='产线'),
        ),
    ]
