# Generated by Django 5.1.2 on 2026-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_taskplan_phase_taskplan_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_add_cases',
            field=models.BooleanField(default=False, verbose_name='可添加任务计划'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_delete_cases',
            field=models.BooleanField(default=False, verbose_name='可删除任务计划'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_edit_cases',
            field=models.BooleanField(default=False, verbose_name='可编辑任务计划'),
        ),
    ]
