# Generated by Django 5.1.2 on 2026-01-19 11:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0018_alter_userprofile_can_add_cases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', '用户登录'), ('logout', '用户登出'), ('create_asset', '创建资产'), ('edit_asset', '编辑资产'), ('create_maintenance', '创建维护记录'), ('edit_maintenance', '编辑维护记录'), ('create_task_plan', '创建任务计划'), ('edit_task_plan', '编辑任务计划'), ('view_dashboard', '查看仪表板'), ('other', '其他活动')], max_length=50, verbose_name='活动类型')),
                ('description', models.TextField(blank=True, verbose_name='活动描述')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间戳')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyVisitTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('visit_count', models.IntegerField(default=0, verbose_name='访问次数')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='独立访客数')),
            ],
            options={
                'verbose_name': '每周访问趋势',
                'verbose_name_plural': '每周访问趋势',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
