# Generated by Django 5.1.2 on 2026-02-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0019_useractivity_weeklyvisittrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemanual',
            name='phase',
            field=models.CharField(blank=True, choices=[('phase_1', '一期'), ('phase_2', '二期')], max_length=20, null=True, verbose_name='工厂分期'),
        ),
    ]
