# Generated by Django 5.1.2 on 2026-02-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0020_maintenancemanual_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancemanual',
            name='phase',
        ),
    ]
