# Generated by Django 5.1.2 on 2026-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0021_remove_maintenancemanual_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemanual',
            name='phase',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='期数'),
        ),
    ]
